import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from '@next/third-parties/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="border-b mb-8 p-4">
          <div className="max-w-4xl mx-auto flex justify-between items-center">
            <Link href="/" className="font-bold text-xl">
              Kurabiye Log
            </Link>
            <div className="space-x-4">
              <Link href="/" className="hover:text-blue-500">
                Haberler
              </Link>
              <Link href="/rehberler" className="hover:text-blue-500">
                Rehberler
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
      <GoogleAnalytics gaId="G-NMGCN59YR3" />
    </html>
  );
}
